// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MotorsCommand.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MotorsCommand.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace gazebo {
namespace msgs {
class MotorsCommandDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<MotorsCommand> {
} _MotorsCommand_default_instance_;

namespace protobuf_MotorsCommand_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MotorsCommand, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MotorsCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MotorsCommand, left_torque_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MotorsCommand, right_torque_),
  0,
  1,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 6, sizeof(MotorsCommand)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_MotorsCommand_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "MotorsCommand.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _MotorsCommand_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _MotorsCommand_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\023MotorsCommand.proto\022\013gazebo.msgs\":\n\rMo"
      "torsCommand\022\023\n\013left_torque\030\001 \002(\002\022\024\n\014righ"
      "t_torque\030\002 \002(\002"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 94);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MotorsCommand.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_MotorsCommand_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MotorsCommand::kLeftTorqueFieldNumber;
const int MotorsCommand::kRightTorqueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MotorsCommand::MotorsCommand()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_MotorsCommand_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:gazebo.msgs.MotorsCommand)
}
MotorsCommand::MotorsCommand(const MotorsCommand& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&left_torque_, &from.left_torque_,
    reinterpret_cast<char*>(&right_torque_) -
    reinterpret_cast<char*>(&left_torque_) + sizeof(right_torque_));
  // @@protoc_insertion_point(copy_constructor:gazebo.msgs.MotorsCommand)
}

void MotorsCommand::SharedCtor() {
  _cached_size_ = 0;
  ::memset(&left_torque_, 0, reinterpret_cast<char*>(&right_torque_) -
    reinterpret_cast<char*>(&left_torque_) + sizeof(right_torque_));
}

MotorsCommand::~MotorsCommand() {
  // @@protoc_insertion_point(destructor:gazebo.msgs.MotorsCommand)
  SharedDtor();
}

void MotorsCommand::SharedDtor() {
}

void MotorsCommand::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MotorsCommand::descriptor() {
  protobuf_MotorsCommand_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_MotorsCommand_2eproto::file_level_metadata[0].descriptor;
}

const MotorsCommand& MotorsCommand::default_instance() {
  protobuf_MotorsCommand_2eproto::InitDefaults();
  return *internal_default_instance();
}

MotorsCommand* MotorsCommand::New(::google::protobuf::Arena* arena) const {
  MotorsCommand* n = new MotorsCommand;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MotorsCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:gazebo.msgs.MotorsCommand)
  if (_has_bits_[0 / 32] & 3u) {
    ::memset(&left_torque_, 0, reinterpret_cast<char*>(&right_torque_) -
      reinterpret_cast<char*>(&left_torque_) + sizeof(right_torque_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool MotorsCommand::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:gazebo.msgs.MotorsCommand)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required float left_torque = 1;
      case 1: {
        if (tag == 13u) {
          set_has_left_torque();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &left_torque_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required float right_torque = 2;
      case 2: {
        if (tag == 21u) {
          set_has_right_torque();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &right_torque_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:gazebo.msgs.MotorsCommand)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:gazebo.msgs.MotorsCommand)
  return false;
#undef DO_
}

void MotorsCommand::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:gazebo.msgs.MotorsCommand)
  // required float left_torque = 1;
  if (has_left_torque()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->left_torque(), output);
  }

  // required float right_torque = 2;
  if (has_right_torque()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->right_torque(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:gazebo.msgs.MotorsCommand)
}

::google::protobuf::uint8* MotorsCommand::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:gazebo.msgs.MotorsCommand)
  // required float left_torque = 1;
  if (has_left_torque()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->left_torque(), target);
  }

  // required float right_torque = 2;
  if (has_right_torque()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->right_torque(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gazebo.msgs.MotorsCommand)
  return target;
}

size_t MotorsCommand::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:gazebo.msgs.MotorsCommand)
  size_t total_size = 0;

  if (has_left_torque()) {
    // required float left_torque = 1;
    total_size += 1 + 4;
  }

  if (has_right_torque()) {
    // required float right_torque = 2;
    total_size += 1 + 4;
  }

  return total_size;
}
size_t MotorsCommand::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gazebo.msgs.MotorsCommand)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required float left_torque = 1;
    total_size += 1 + 4;

    // required float right_torque = 2;
    total_size += 1 + 4;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MotorsCommand::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:gazebo.msgs.MotorsCommand)
  GOOGLE_DCHECK_NE(&from, this);
  const MotorsCommand* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MotorsCommand>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:gazebo.msgs.MotorsCommand)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:gazebo.msgs.MotorsCommand)
    MergeFrom(*source);
  }
}

void MotorsCommand::MergeFrom(const MotorsCommand& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:gazebo.msgs.MotorsCommand)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._has_bits_[0 / 32] & 3u) {
    if (from.has_left_torque()) {
      set_left_torque(from.left_torque());
    }
    if (from.has_right_torque()) {
      set_right_torque(from.right_torque());
    }
  }
}

void MotorsCommand::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:gazebo.msgs.MotorsCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MotorsCommand::CopyFrom(const MotorsCommand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gazebo.msgs.MotorsCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MotorsCommand::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  return true;
}

void MotorsCommand::Swap(MotorsCommand* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MotorsCommand::InternalSwap(MotorsCommand* other) {
  std::swap(left_torque_, other->left_torque_);
  std::swap(right_torque_, other->right_torque_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MotorsCommand::GetMetadata() const {
  protobuf_MotorsCommand_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_MotorsCommand_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MotorsCommand

// required float left_torque = 1;
bool MotorsCommand::has_left_torque() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void MotorsCommand::set_has_left_torque() {
  _has_bits_[0] |= 0x00000001u;
}
void MotorsCommand::clear_has_left_torque() {
  _has_bits_[0] &= ~0x00000001u;
}
void MotorsCommand::clear_left_torque() {
  left_torque_ = 0;
  clear_has_left_torque();
}
float MotorsCommand::left_torque() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.MotorsCommand.left_torque)
  return left_torque_;
}
void MotorsCommand::set_left_torque(float value) {
  set_has_left_torque();
  left_torque_ = value;
  // @@protoc_insertion_point(field_set:gazebo.msgs.MotorsCommand.left_torque)
}

// required float right_torque = 2;
bool MotorsCommand::has_right_torque() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void MotorsCommand::set_has_right_torque() {
  _has_bits_[0] |= 0x00000002u;
}
void MotorsCommand::clear_has_right_torque() {
  _has_bits_[0] &= ~0x00000002u;
}
void MotorsCommand::clear_right_torque() {
  right_torque_ = 0;
  clear_has_right_torque();
}
float MotorsCommand::right_torque() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.MotorsCommand.right_torque)
  return right_torque_;
}
void MotorsCommand::set_right_torque(float value) {
  set_has_right_torque();
  right_torque_ = value;
  // @@protoc_insertion_point(field_set:gazebo.msgs.MotorsCommand.right_torque)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace gazebo

// @@protoc_insertion_point(global_scope)
